package relayobserver

import (
	"context"
	"net"
	"time"

	"github.com/QuantumNous/new-api/relaykit/dto"
	"github.com/google/uuid"
)

// This file holds the frozen data contracts of the observer: the turn event,
// the status snapshot, and the store port. It must stay free of database
// driver imports: all PostgreSQL code lives in the adapter (store_pg*.go)
// that implements the Store port.

// ContentState describes how the request content of a turn was captured.
const (
	// ContentStateFull marks a turn whose content was captured normally.
	ContentStateFull = "full"
	// ContentStateMetadataOnly marks an oversized or unparseable request that
	// produced no content rows.
	ContentStateMetadataOnly = "metadata_only"
	// ContentStateGap marks a turn whose content has an explicit gap marker
	// (for example a truncated tail). The marker is data, not silent loss.
	ContentStateGap = "gap"
)

// IPTrust is the frozen, single-source trust tier of a turn's IP capture:
// "direct" (RemoteAddr origin), "proxy" (derived through a trusted proxy),
// or "none" (capture off). Every turn carries a tier — "none" while the
// dual-opt-in RecordIP policy is off. Event and Status both carry this type,
// and the adapter maps it verbatim to the ip_trust column; T1.3 and T2.5
// consume these constants instead of redefining or translating values.
type IPTrust string

const (
	// IPTrustDirect marks a peer taken from RemoteAddr.
	IPTrustDirect IPTrust = "direct"
	// IPTrustProxy marks a peer derived through a trusted proxy.
	IPTrustProxy IPTrust = "proxy"
	// IPTrustNone marks capture off; the effective tier while the
	// dual-opt-in RecordIP policy is disabled.
	IPTrustNone IPTrust = "none"
)

// Event is the frozen turn-level record created by exactly one client request.
// It maps one-to-one to the observer_turns table (the row id is generated by
// the store). The NewAPI request id plus node scope is the idempotency key.
//
// The event is body-free in its serialized form: request content and session
// aliases are captured separately by the worker (T2.6), which reads the
// zero-copy Request reference and Identity material below and never keeps
// them in the written row. It carries no endpoint, URL, or credential fields.
type Event struct {
	EventID   string
	NodeScope string

	SessionID  *uuid.UUID
	OccurredAt time.Time

	UserID        int64
	TokenID       int64
	ClientProfile string
	Model         string
	UpstreamModel string
	// RelayFormat is the final upstream request format persisted on the turn.
	RelayFormat string
	// CaptureRelayFormat is the original client request format paired with
	// Request. It is worker-only and is not persisted; conversion chains may
	// leave Request as a Claude/Responses DTO while RelayFormat records the
	// final OpenAI upstream format. Empty falls back to RelayFormat for events
	// created outside the request path and for backward-compatible tests.
	CaptureRelayFormat string

	Success    bool
	StatusCode int
	ErrorType  string
	ErrorCode  string

	LatencyMS       int64
	FirstResponseMS int64
	Stream          bool

	PromptTokens     int64
	CompletionTokens int64
	CachedTokens     int64
	Quota            int64

	// Attempts holds the bounded downstream attempt summary; entries beyond
	// the cap are omitted and counted in AttemptsOmitted by the request side.
	Attempts        []AttemptSummary
	AttemptsOmitted int

	// ClientIP and the geo fields are populated only under the dual-opt-in
	// RecordIP policy; they are Root-only at the API layer.
	ClientIP net.IP
	// IPTrust is the source trust tier of this turn; the adapter maps it
	// verbatim to the ip_trust column.
	IPTrust     IPTrust
	CountryCode string
	Country     string
	City        string
	ASN         int64
	ASNOrg      string

	// Request is the already parsed relay request DTO (the relayInfo.Request
	// reference) attached by the request path as a zero-copy reference (T2.6).
	// The worker reads it for worker-side content normalization; the request
	// path must not write it after the channel send that admits the event —
	// the send establishes happens-before, so the worker's read is race-free
	// (SSOT Isolation Contract). A nil request means no content capture: the
	// event stays metadata-only.
	Request *dto.Request

	// Identity carries the request's session-identity material (headers and
	// raw body byte references, zero-copy) for worker-side alias resolution.
	// It is snapshotted before the send under the same happens-before rule as
	// Request: neither the header map nor the body bytes are written by the
	// request path afterwards. An empty body or missing headers degrade
	// identity resolution, never the event.
	Identity IdentityInput

	ContentState string
}

// AttemptSummary is one bounded downstream channel attempt: channel id, group,
// status/error code, and elapsed milliseconds. The JSON tags serve the Root
// turn DTO (T3.2); the observer itself never serializes attempts directly.
type AttemptSummary struct {
	ChannelID  int64  `json:"channel_id"`
	Group      string `json:"group"`
	StatusCode int    `json:"status_code"`
	ErrorCode  string `json:"error_code"`
	ElapsedMS  int64  `json:"elapsed_ms"`
}

// ReasonCode is a stable, secret-free reason for a disabled or degraded
// observer. It replaces free-form error strings in the status contract: raw
// errors (database internals, DSN parse details, config text) never cross the
// status, API, or log boundary — logs carry only a redacted classification
// and its context, never the raw error text. The empty value means healthy.
type ReasonCode string

const (
	// ReasonDisabled marks an observer explicitly turned off by configuration.
	ReasonDisabled ReasonCode = "disabled"
	// ReasonConfigInvalid marks configuration that failed to parse.
	ReasonConfigInvalid ReasonCode = "config_invalid"
	// ReasonStoreInitFailed marks a store that could not be initialized, for
	// example an unreachable database or an unsupported DSN.
	ReasonStoreInitFailed ReasonCode = "store_init_failed"
	// ReasonSchemaMismatch marks a schema version mismatch at verify startup.
	ReasonSchemaMismatch ReasonCode = "schema_mismatch"
	// ReasonHMACKeyMissing marks an observer enabled without an HMAC key.
	// Without the key the observer cannot derive session identity digests or
	// verify reconstructed content, so it self-disables instead of running in
	// a misleading metadata-only-but-healthy state.
	ReasonHMACKeyMissing ReasonCode = "hmac_key_missing"
	// ReasonCircuitOpen marks an open write circuit: batch writes keep failing
	// and the worker pauses until the cooldown expires.
	ReasonCircuitOpen ReasonCode = "circuit_open"
	// ReasonQueryDegraded marks a degraded Root query surface; the writer core
	// does not set it.
	ReasonQueryDegraded ReasonCode = "query_degraded"
)

// Status is a point-in-time snapshot of observer state for GET /status and
// the Overview page. It is assembled from in-memory counters only and never
// contains secrets, DSNs, HMAC keys, or event content. Counter fields are
// totals since process start.
type Status struct {
	Enabled bool
	// ReasonCode explains a disabled or degraded observer (for example
	// config_invalid or store_init_failed); empty when healthy. The raw error
	// behind a code never crosses the status, API, or log boundary — logs see
	// only the redacted classification and context.
	ReasonCode ReasonCode
	// IPTrust is the effective trust tier of the running configuration; the
	// same IPTrust values as the per-turn field, "none" while capture is off.
	IPTrust IPTrust

	QueueCount int
	QueueBytes int64

	AcceptedTotal int64
	WrittenTotal  int64
	DroppedTotal  int64

	CircuitOpen bool
	// CircuitCooldown is the remaining cooldown of an open circuit; zero when
	// the circuit is closed or the cooldown has expired.
	CircuitCooldown time.Duration
	// PGLatencyMS is the duration of the most recent completed batch write in
	// milliseconds; -1 when no write has completed.
	PGLatencyMS int64

	// ContentGapsTotal counts turns whose content capture ended with a gap
	// marker or metadata-only state.
	ContentGapsTotal int64

	// RecentVolume counts events accepted in the current wall-clock second.
	// The packed runtime bucket expires by timestamp, independent of flushing.
	RecentVolume int64

	// LastRetentionPass is the completion time of the most recent retention
	// pass (successful or failed); the zero value means no pass has run yet.
	LastRetentionPass time.Time
	// RetentionTurnsDeleted / RetentionSessionsDeleted / RetentionObjectsDeleted
	// count rows deleted by retention passes since process start.
	RetentionTurnsDeleted    int64
	RetentionSessionsDeleted int64
	RetentionObjectsDeleted  int64
	// RetentionFailures counts retention passes aborted by an error; the
	// next scheduled pass retries.
	RetentionFailures int64
}

// Store is the writer-facing persistence port of the observer. Only the
// PostgreSQL adapter (store_pg*.go) implements it; core logic and tests use a
// fake store. This file must never import a database driver: adapters own all
// driver, pool, and schema code.
//
// Store construction (opening the dedicated pool, schema verify/bootstrap,
// and rejecting non-PostgreSQL DSNs) is adapter-owned and returns an error on
// failure; the caller disables the observer with that error as the reason.
// Query and retention surfaces are additive extensions of this port added by
// their owning phases; core code does not depend on them.
//
// Shutdown contract: the runtime stops the worker inside the hard two-second
// shutdown budget, drops remaining events, and counts them; it never waits
// indefinitely for the store. Every method therefore takes a context and must
// return when it expires: WriteBatch receives the per-write timeout, and
// Close receives the remaining shutdown budget.
type Store interface {
	// WriteBatch persists a batch of turn events in one idempotent
	// transaction. Duplicate (node_scope, event_id) rows are skipped
	// (ON CONFLICT DO NOTHING). Any error drops the batch at the caller and
	// opens the circuit; the observer never retries a failed batch. The
	// context carries the write timeout and must be respected.
	WriteBatch(ctx context.Context, events []Event) error
	// AppendTurns persists the captured content of one or more batch turns in
	// one idempotent transaction (T2.3/T2.6; see ContentPersistence for the
	// full per-turn contract). The worker calls it after WriteBatch: a
	// failure leaves the metadata rows written, so the caller keeps the
	// appends and retries them on the next pass — metadata is idempotent and
	// never duplicated, and content objects dedup per (session, digest).
	AppendTurns(ctx context.Context, turns []ContentInput) error
	// Close releases the store's connections, is idempotent, and must return
	// before ctx expires. The runtime passes the remaining shutdown budget.
	Close(ctx context.Context) error
}
